// <auto-generated />
using System;
using FitnessReservationAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessReservationAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessReservationAPI.Models.FitnessReservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("KeyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.ToTable("FitnessReservations");
                });

            modelBuilder.Entity("FitnessReservationAPI.Models.KeyMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KeyMasters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            KeyNumber = "710"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            KeyNumber = "711"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            KeyNumber = "712"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            KeyNumber = "713"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            KeyNumber = "714"
                        });
                });

            modelBuilder.Entity("FitnessReservationAPI.Models.FitnessReservation", b =>
                {
                    b.HasOne("FitnessReservationAPI.Models.KeyMaster", "KeyMaster")
                        .WithMany("Reservations")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KeyMaster");
                });

            modelBuilder.Entity("FitnessReservationAPI.Models.KeyMaster", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
